#!/usr/bin/env php
<?php

$installed_vendor_path = dirname(dirname(dirname(__FILE__))) . '/autoload.php';
$local_vendor_path = dirname(__FILE__) . '/vendor/autoload.php';

// If installed, use top level path, otherwise use local path
if (file_exists(($installed_vendor_path))) {
    require_once($installed_vendor_path);
}
else if (file_exists($local_vendor_path)) {
    require_once($local_vendor_path);
}


use \Wjdhollow\Glob\AntGlob;

$directory = $argv[1];
$pattern = $argv[2];

$glob = new AntGlob($pattern);

$names = $glob->inDirectory($directory);
foreach ($names as $name) {
    echo $name . PHP_EOL;
}
exit(0);